name: Deploy janxzj.com
on:
  push:
    branches:
      - master
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out brunnerliv.io
        uses: actions/checkout@master
        with:
          repository: brunnerlivio/brunnerliv.io
          path: brunnerliv.io
      - run: |
          cd brunnerliv.io
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name 'Livio Brunner'
          git config --global user.email 'livio.brunner.lb1@gmail.com'
          git submodule update --remote --init --recursive
          git add -A .
          git commit -m "Update submodule"
          git push --force "https://brunnerlivio:${{ secrets.API_TOKEN_GITHUB }}@github.com/BrunnerLivio/brunnerliv.io.git" master:master
          
